#!/bin/sh

# Set needed files as accessable for the configured user
chown -R nobody:staff /opt/appserver/var
chown -R nobody:staff /opt/appserver/webapps
chown -R nobody:staff /opt/appserver/deploy

# Start the services
/opt/appserver/sbin/appserverctl start
/opt/appserver/sbin/appserver-watcherctl start
/opt/appserver/sbin/appserver-php5-fpmctl start

exit 0
