#!/bin/sh

# Setup appserver by calling server.php with -s install to trigger install mode setup
cd /opt/appserver
./server.php -s install

# Start the services
/opt/appserver/sbin/appserverctl start
/opt/appserver/sbin/appserver-watcherctl start
/opt/appserver/sbin/appserver-php5-fpmctl start

exit 0
