#!/bin/sh

# Setup appserver by calling server.php with -s install to trigger install mode setup
/opt/appserver/server.php -s install

# run postinstall script from appserver-io/appserver composer package
# to set correct path for specific startup scripts
cd /opt/appserver
./bin/php ./bin/composer.phar run-script post-install-cmd

# Start the services
/opt/appserver/sbin/appserverctl start
/opt/appserver/sbin/appserver-watcherctl start
/opt/appserver/sbin/appserver-php5-fpmctl start

exit 0
