#!/bin/sh

# Set needed files as accessable for the configured user
chown -R nobody:staff /opt/appserver/var
chown -R nobody:staff /opt/appserver/webapps
chown -R nobody:staff /opt/appserver/deploy

# run postinstall script from appserver-io/appserver composer package
# to set correct path for specific startup scripts
cd /opt/appserver
./bin/php ./bin/composer.phar run-script post-install-cmd

# Start the services
/opt/appserver/sbin/appserverctl start
/opt/appserver/sbin/appserver-watcherctl start
/opt/appserver/sbin/appserver-php5-fpmctl start

exit 0
